#!/bin/bash

# Find out more about unattended key generation at
# https://www.gnupg.org/documentation/manuals/gnupg/Unattended-GPG-key-generation.html

PSEUDO_NAME=$(cat /proc/sys/kernel/random/uuid)
echo "
    %pubring ./secret/$1.pub
    %secring ./secret/$1.sec
    Key-Type: RSA
    Key-Length: 4096
    Subkey-Type: RSA
    Subkey-Length: 4096
    Name-Real: $PSEUDO_NAME
    Expire-Date: 0
    %commit
    %echo done
" | gpg --batch --verbose --no-default-keyring --gen-key
