#!/bin/bash

# See https://www.linuxquestions.org/questions/programming-9/bash-script-return-full-path-and-filename-680368/page3.html#post4309783
function abspath {
    if [[ -d "$1" ]] ; then
        pushd "$1" >/dev/null
        pwd
        popd >/dev/null
    elif [[ -e $1 ]] ; then
        pushd $(dirname $1) >/dev/null
        echo $(pwd)/$(basename $1)
        popd >/dev/null
    else
        # the function could not resolve the full path, this is likely an error
        # but I return the original string
        echo "$1"
    fi
}

# Interprets the command line to identify the requested operation (case
# insensitive)
case $(echo "${1,,}") in
    "createrecipient" ) OPERATION="createrecipient" ;; # supports multiple --shadow
    "gist" ) OPERATION="readgist" ;;
    "status" ) OPERATION="readstatus" ;;
    "timeline" ) OPERATION="timeline" ;;
    "update" ) OPERATION="update" ;; # supports multiple --shadow
    "version" ) OPERATION="showversion" ;;
    * )
        echo "Command '$1' not recognized."
        exit 1
        ;;
esac

# Interprets the parameters following the command
shift
MYSHADOW_HOMES=""
while true; do
    case "$1" in
        "" ) # no more parameters to process
            break ;;
        -s | --shadow )
            if [ "$MYSHADOW_HOMES" = "" ] ; then
                MYSHADOW_HOMES=$(abspath "$2")
            elif [ "$OPERATION" = "createrecipient" ] || [ "$OPERATION" = "update" ] ; then
                # TODO: should I warn the user when multiple --shadow are
                # specified for unsupported commands?
                MYSHADOW_HOMES="$MYSHADOW_HOMES:"$(abspath "$2")
            fi
            shift 2
            ;;
        -t | --twitter )
            TWITTER=true ; shift ;;
        * )
            case "$OPERATION" in
                "createrecipient" ) RECIPIENT_NICKNAME="$1" ; shift ;;
                "readgist"        ) GIST_URL="$1" ; shift ;;
                "readstatus"      ) STATUS_ID="$1" ; shift ;;
                "update"          ) INPUT_FILE="$1" ; shift ;;
            esac ;;
    esac
done

# Sets the default keypair folder, if none was specified
if [ "$MYSHADOW_HOMES" = "" ] ; then
    MYSHADOW_HOMES=$(abspath "$HOME/.myshadow")
fi

# Creates the specified my-shadow keypair folders if they don't exist
for MYSHADOW_HOME in $(echo $MYSHADOW_HOMES | sed "s/:/ /g") ; do
    mkdir -p $MYSHADOW_HOME
done

case "$OPERATION" in

    "createrecipient" )

        # ******************************************************************* #
        for MYSHADOW_HOME in $(echo $MYSHADOW_HOMES | sed "s/:/ /g") ; do
            # Find out more about unattended key generation at
            # https://www.gnupg.org/documentation/manuals/gnupg/Unattended-GPG-key-generation.html
            PSEUDO_NAME=$(cat /proc/sys/kernel/random/uuid)
            echo "
                %pubring $MYSHADOW_HOME/$RECIPIENT_NICKNAME.pub
                %secring $MYSHADOW_HOME/$RECIPIENT_NICKNAME.sec
                Key-Type: RSA
                Key-Length: 4096
                Subkey-Type: RSA
                Subkey-Length: 4096
                Name-Real: $PSEUDO_NAME
                Expire-Date: 0
                %commit
                %echo done
            " | gpg --batch --verbose --no-default-keyring --gen-key
        done
        # ******************************************************************* #
        ;;

    "readgist" )

        # ******************************************************************* #
        TEMP_FILE="/tmp/$(cat /proc/sys/kernel/random/uuid).asc"
        wget -qO - $GIST_URL > $TEMP_FILE
        COMMAND="gpg -dq --no-default-keyring"
        PRIVATE_KEYS="$MYSHADOW_HOMES/*.sec"
        for FILE in $PRIVATE_KEYS; do
            COMMAND="$COMMAND --secret-keyring $FILE --keyring $MYSHADOW_HOMES/$(basename $FILE .sec).pub"
        done
        DECRYPTED_MESSAGE="$($COMMAND $TEMP_FILE 2> $TEMP_FILE.error)"
        # Two errors can happen here:
        # - "gpg: no valid OpenPGP data found." if there is no OpenPGP data at that URL, or
        # - "gpg: decryption failed: secret key not available" if I don't have any suitable key
        # Often, another general "gpg: decrypt_message failed: eof" error may be printed, too
        ERROR=$(cat $TEMP_FILE.error)
        ERROR_CHARACTERS=$(echo "$ERROR" | wc -m)
        if echo "$ERROR" | grep -qE "gpg: no valid OpenPGP data found"; then
            DECRYPTED_MESSAGE="my-shadow: no valid my-shadow data found"
        elif echo "$ERROR" | grep -qE "gpg: decryption failed: secret key not available"; then
            DECRYPTED_MESSAGE="my-shadow: decryption failed: secret key not available"
        elif [ "$ERROR_CHARACTERS" -gt "1" ]; then
            DECRYPTED_MESSAGE="my-shadow: unknown error"
        fi
        if [ "$TWITTER" = "true" ] && [ ${#DECRYPTED_MESSAGE} -ge 135 ] ; then
            # see http://askubuntu.com/a/513772/581904 for the magical sed command;
            # it's the only one that really worked
            DECRYPTED_MESSAGE=$(echo "$DECRYPTED_MESSAGE" | sed -e :a -e '/$/N; s/\n/ /; ta' | cut -c1-134)" (...)"
        fi
        echo "$DECRYPTED_MESSAGE"
        rm -f $TEMP_FILE $TEMP_FILE.error
        # ******************************************************************* #
        ;;

    "readstatus" )

        # ******************************************************************* #
        COMMAND="myshadow gist --shadow $MYSHADOW_HOMES"
        if [ "$TWITTER" = "true" ] ; then
            COMMAND="$COMMAND --twitter"
        fi
        # TODO: manage the situation when the status id does not exist. t
        # outputs an error like "/usr/local/bin/t: No status found with that ID."
        GIST_URL="$(t status --csv --decode-uris --profile=$MYSHADOW_HOMES/twitter.credentials $STATUS_ID | csvfix order -smq -ifn -f 4)"
        # TODO: manage the situation when the status id does not exist. t
        # outputs an error like "/usr/local/bin/t: No status found with that ID."
        # TODO: manage the situation when the status id exists but it is not a
        # valid my-secret gist
        $COMMAND $GIST_URL
        # ******************************************************************* #
        ;;

    "timeline" )

        # ******************************************************************* #
        FEED="$(t timeline --csv --decode-uris --profile=$MYSHADOW_HOMES/twitter.credentials)"
        NEW_FEED=$(echo -e "$FEED" | head -1)
        FEED=$(echo -e "$FEED" | tail -n +2)
        IFS=$'\n' # see http://superuser.com/q/284187/626788
        for LINE in $FEED; do
            if echo "$LINE" | grep -qE "https://gist.github.com/anonymous/[a-z0-9]{32}/raw"; then
                GIST_URL=$(echo "$LINE" | csvfix order -smq -f 4)
                # note the escaping of any double quotes in the sed command below
                DECRYPTED_STATUS=$(myshadow gist --shadow $MYSHADOW_HOMES --twitter $GIST_URL | sed -e s/\"/\\\"/g)
                LINE=$(echo "$LINE" | csvfix edit -smq -f 4 -e "s/.*/$DECRYPTED_STATUS/")
            fi
            NEW_FEED="$NEW_FEED"$'\n'"$LINE"
        done
        echo -e "$NEW_FEED"
        # ******************************************************************* #
        ;;

    "update" )

        # ******************************************************************* #
        if [ "$INPUT_FILE" = "" ] ; then
            echo "Write your update and terminate with CTRL-D..."
            CLEAR_TEXT=$(cat)
            echo "Sending..."
        else
            CLEAR_TEXT=$(cat "$INPUT_FILE")
        fi
        for MYSHADOW_HOME in $(echo $MYSHADOW_HOMES | sed "s/:/ /g") ; do
            TEMP_FILE="/tmp/$(cat /proc/sys/kernel/random/uuid).asc"
            COMMAND="gpg -ea --output $TEMP_FILE --always-trust"
            PUBLIC_KEYS=$MYSHADOW_HOME/*.pub
            for FILE in $PUBLIC_KEYS; do
                COMMAND="$COMMAND --keyring $FILE -r $(gpg --no-default-keyring --keyring $FILE --list-keys | grep "^sub" | grep -Po '(?<=/)[A-Z0-9]{8}(?= )')"
            done
            echo "$CLEAR_TEXT" | $COMMAND
            GIST_URL=$(gist --raw --anonymous --private $TEMP_FILE)
            t update "$GIST_URL" --profile=$MYSHADOW_HOME/twitter.credentials > /dev/null
            rm -f $TEMP_FILE
        done
        # ******************************************************************* #
        ;;

    "showversion" )

        # ******************************************************************* #
        echo "my-secret 0.0.45
Copyright (C) 2017 Digital Contraptions Imaginarium Ltd.
License MIT <https://raw.githubusercontent.com/Digital-Contraptions-Imaginarium/my-shadow/master/LICENSE>

Home: $MYSHADOW_HOME"
        # ******************************************************************* #
        ;;

esac
